Interfaz
samuelmarinsoto/eagledefender pull request #1
Opened 2023-10-02 03:01 UTC by joscCE

aqui esta la interfaz para que revisen el progreso y me la acepten, gracias <3

2023-10-02 03:07 UTC, Angelo-CE commented
nose.py  ? minds?

2023-10-02 03:09 UTC, samuelmarinsoto commented
mae no que esta picha legalmente. como quiere que acepte esta cochinada

2023-10-02 03:10 UTC, IsaacWZ requested changes
Como va a poner .pys que no hacen nada, mae.
Recuerde que estamos usando Google Docstrings

2023-10-02 03:10 UTC, IsaacWZ commented on update_login.py
> +# def registrarse():
Qué es esto mae?????

2023-10-02 03:10 UTC, IsaacWZ commented on registro.py
> +class Registro(customtkinter.CTk):
Comente las varas mae

2023-10-02 03:10 UTC, IsaacWZ commented on nose.py
> +class App(customtkinter.CTk):
Mae como que nose.py
COMENTEEEE CON GOOGLE DOCSTRINGS MAE

2023-10-02 03:10 UTC, IsaacWZ commented on menu.py
> +class Menu_principal(customtkinter.CTk):
Al menos aquí dice menú mae

2023-10-02 03:11 UTC, samuelmarinsoto requested changes
arregle esta picha mae

2023-10-03 01:58 UTC, samuelmarinsoto approved these changes
ta weno, grasias

2023-10-03 01:59 UTC, Angelo-CE approved these changes

2023-10-03 02:00 UTC, merged